# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20151223_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=b''),
        ),
    ]
